profiles:
    test:
        path-format: '.+'
        rules:
            if:
                path-format: '.+\.go'
                modifiers:
                    -   kind: trim-prefix
                        prefix: 'test 1'
                    -   kind: trim-suffix
                        suffix: 'test 2'
                    -   kind: to-lower
                filters:
                    -   kind: contains
                        line: 'if '
