profiles:
    default:
        path-format: '.+'
        rules:
            lines: &lines
                path-format: '.+'
                modifiers: [ ]
                filters:
                    -   kind: any
            blank: &blank
                path-format: '.+'
                modifiers: &m-trim-spaces
                    -   kind: trim-spaces
                filters:
                    -   kind: blank

    go:
        path-format: '.+\.go$'
        rules: &r-go
            lines: *lines
            blank: *blank
            comments:
                path-format: '.+'
                modifiers: *m-trim-spaces
                filters:
                    - &f-comment
                        kind: union
                        filter-a: &f-multiline-comment
                            kind: multiline
                            start-filter:
                                kind: contains
                                line: '/*'
                            end-filter:
                                kind: contains
                                line: '*/'
                        filter-b: &f-one-line-comment
                            kind: regexp
                            pattern: '^//'
            code:
                path-format: '.+'
                modifiers: *m-trim-spaces
                filters:
                    -   kind: not
                        filter:
                            kind: blank
                    -   kind: not
                        filter: *f-comment

    go-extended:
        path-format: '.+\.go$'
        rules:
            <<: *r-go
            one-line-comments:
                path-format: '.+'
                modifiers: *m-trim-spaces
                filters:
                    - *f-one-line-comment
            multiline-comments:
                path-format: '.+'
                modifiers: *m-trim-spaces
                filters:
                    - *f-multiline-comment

