profiles:
    default:
        path-format: '.+'
        rules:
            new-line: &new-line
                path-format: '.+'
                modifiers: [ ]
                filters:
                    -   kind: any
            blank: &blank
                path-format: '.+'
                modifiers:
                    -   kind: trim-spaces
                filters:
                    -   kind: blank

    go:
        path-format: '.+\.go$'
        rules:
            new-line: *new-line
            blank: *blank
            comments:
                path-format: '.+'
                modifiers: &trim-spaces
                    -   kind: trim-spaces
                filters:
                    - &comment
                        kind: union
                        filter-a: &multiline-comment
                            kind: multiline
                            start-filter:
                                kind: contains
                                line: '/*'
                            end-filter:
                                kind: contains
                                line: '*/'
                        filter-b: &one-line-comment
                            kind: regexp
                            pattern: '^//'
            one-line-comments:
                path-format: '.+'
                modifiers: *trim-spaces
                filters:
                    - *one-line-comment
            multiline-comments:
                path-format: '.+'
                modifiers: *trim-spaces
                filters:
                    - *multiline-comment
            code:
                path-format: '.+'
                modifiers: *trim-spaces
                filters:
                    -   kind: not
                        filter: *comment
