profiles:
    Default:
        path-format: .+
        rules:
            new-line:
                path-format: .+
                modifiers: []
                filters:
                    - kind: any
            blank:
                path-format: .+
                modifiers:
                    - kind: trim-spaces
                filters:
                    - kind: blank

    Go:
        path-format: ".+\\.go"
        rules:
            comments:
                path-format: .+
                modifiers:
                    - kind: trim-spaces
                filters:
                    - kind: union
                      filter-a:
                          kind: multiline
                          start-filter:
                              kind: contains
                              line: "/*"
                          end-filter:
                              kind: contains
                              line: "*/"
                      filter-b:
                          kind: regexp
                          pattern: "^//"
            one-line-comments:
                path-format: .+
                modifiers:
                    - kind: trim-spaces
                filters:
                    - kind: regexp
                      pattern: "^//"
            multiline-comments:
                path-format: .+
                modifiers:
                    - kind: trim-spaces
                filters:
                    - kind: multiline
                      start-filter:
                          kind: contains
                          line: "/*"
                      end-filter:
                          kind: contains
                          line: "*/"
